// Admin controls always use Thai. These labels never translate saved site copy.
const CMS_ADMIN_LABELS = {
  'line contact':'ปุ่ม LINE ลอย','floating button label':'ชื่อปุ่มลอย','introduction':'ข้อความนำ','description':'คำอธิบาย','contact button':'ปุ่มติดต่อ',
  'facebook':'Facebook','advisor profile':'ข้อมูลผู้ให้คำปรึกษา','contact submission':'สถานะการส่งฟอร์ม','calculator design':'ดีไซน์เครื่องคำนวณ','error page':'หน้า Error','cookie consent':'ความยินยอมคุกกี้','shared section labels':'ข้อความร่วมของแต่ละส่วน','home design':'ดีไซน์หน้าเว็บ','home licences':'ส่วนใบอนุญาต','home contact':'ส่วนติดต่อ','footer design':'ดีไซน์ Footer','form messages':'ข้อความแจ้งเตือนฟอร์ม','transparency design':'ส่วนความโปร่งใส','life focus':'ส่วนประกันชีวิต','form choices':'ตัวเลือกในฟอร์ม','business metadata':'ข้อมูลธุรกิจ','calculator labels':'ข้อความเครื่องคำนวณ','renewal form labels':'ข้อความฟอร์มต่ออายุ','consultation form labels':'ข้อความฟอร์มปรึกษา','brand images':'รูปและโลโก้แบรนด์','licences':'ใบอนุญาต','website labels':'ข้อความส่วนกลาง','page composition':'องค์ประกอบหน้าเว็บ','navigation':'เมนูและลิงก์','images & crop':'รูปภาพและ Crop','shared page design':'ดีไซน์ร่วมของหน้าเว็บ','licence band design':'ดีไซน์แถบใบอนุญาต','contact section design':'ดีไซน์ส่วนติดต่อ','featured classes & layout':'ชั้นประกันแนะนำและ Layout',
  'full name (real advisor only)':'ชื่อผู้ให้คำปรึกษา (ข้อมูลจริงเท่านั้น)','personal role':'บทบาทผู้ให้คำปรึกษา','home advisor portrait':'รูปผู้ให้คำปรึกษาบนหน้าแรก','portrait description':'คำอธิบายรูปผู้ให้คำปรึกษา','hero advisor heading':'หัวข้อผู้ให้คำปรึกษาใน Hero','advisor introduction before licence cards':'ข้อความนำก่อนการ์ดใบอนุญาต','contact introduction before name':'ข้อความติดต่อก่อนชื่อ','contact introduction after name':'ข้อความติดต่อหลังชื่อ',
  'submitting':'กำลังส่งข้อมูล','slow':'ส่งข้อมูลช้า','success':'ส่งสำเร็จ','failure':'ส่งไม่สำเร็จ','unknown':'ไม่ทราบผล','limited':'จำกัดการส่ง','title':'หัวข้อ','body':'คำอธิบาย','intro':'ข้อความนำ','line':'ปุ่ม LINE','optional':'ข้อความเพิ่มเติม','retry':'ปุ่มลองใหม่','edit':'ปุ่มแก้ไข','view draft':'ปุ่มดูข้อมูลที่กรอก','hide draft':'ปุ่มซ่อนข้อมูลที่กรอก','services':'ปุ่มดูบริการ','new request':'ปุ่มส่งคำถามใหม่','line help':'ข้อความช่วยเหลือทาง LINE','waiting line':'ปุ่ม LINE ระหว่างรอ','reference':'เลขอ้างอิง','hours':'เวลาทำการ','support':'ความช่วยเหลือ','privacy link':'ลิงก์ความเป็นส่วนตัว','unavailable':'ไม่พร้อมใช้งาน','name required':'แจ้งให้กรอกชื่อ','contact required':'แจ้งให้กรอกช่องทางติดต่อ','consent required':'แจ้งให้ยืนยันความยินยอม','consent changed':'แจ้งข้อความยินยอมเปลี่ยนแปลง','topic too long':'แจ้งรายละเอียดเกินกำหนด','invalid fields':'แจ้งข้อมูลไม่ครบหรือไม่ถูกต้อง',
  'inputs':'ข้อมูลที่ใช้คำนวณ','life':'ประกันชีวิต','ci':'โรคร้ายแรง','health':'ประกันสุขภาพ','statement':'ข้อความสรุป','result statement':'ข้อความสรุปผล','result':'ผลคำนวณ','breakdown':'รายละเอียดผลคำนวณ','total':'ยอดรวม','support cost':'ค่าใช้จ่ายดูแลครอบครัว','transition':'ช่วงปรับตัว','recovery cost':'ค่าใช้จ่ายช่วงพักฟื้น','recovery one off':'ค่าใช้จ่ายพักฟื้นครั้งเดียว','medical buffer':'เงินสำรองค่ารักษา','room daily':'ค่าห้องต่อวัน','details':'รายละเอียด','advice title':'หัวข้อคำแนะนำ','advice body':'รายละเอียดคำแนะนำ','method':'วิธีคำนวณ','method body':'คำอธิบายวิธีคำนวณ','cta':'ข้อความปุ่มหลัก','baht':'หน่วยบาท','per month':'หน่วยต่อเดือน','years':'จำนวนปี','months':'จำนวนเดือน','per day':'หน่วยต่อวัน','spending':'ค่าใช้จ่าย','debt':'หนี้สิน','resources':'ทรัพยากรที่มี','room':'ค่าห้อง','recovery':'การพักฟื้น','photo alt':'คำอธิบายรูป','life result':'ผลประกันชีวิต','ci result':'ผลโรคร้ายแรง','health result':'ผลประกันสุขภาพ','net monthly need':'ความต้องการสุทธิต่อเดือน','room gap':'ส่วนต่างค่าห้อง',
  'monthly need':'ค่าใช้จ่ายจำเป็นต่อเดือน','other monthly income':'รายได้อื่นต่อเดือน','years to support':'จำนวนปีที่ต้องการดูแล','debt to clear':'หนี้ที่ต้องการชำระ','extra lump sum':'เงินก้อนเพิ่มเติม','earmarked assets':'สินทรัพย์ที่เตรียมไว้','existing life cover':'ทุนประกันชีวิตที่มี','monthly recovery need':'ค่าใช้จ่ายพักฟื้นต่อเดือน','recovery months':'จำนวนเดือนพักฟื้น','other support income':'รายได้ช่วยเหลืออื่น','available emergency funds':'เงินสำรองฉุกเฉินที่ใช้ได้','existing critical illness cover':'ทุนโรคร้ายแรงที่มี','extra recovery budget':'งบพักฟื้นเพิ่มเติม','room reference':'ค่าห้องอ้างอิง','custom room daily':'ค่าห้องที่กำหนดเองต่อวัน','room benefit':'สิทธิค่าห้อง','cost sharing':'ค่าใช้จ่ายร่วม','employer cover':'สวัสดิการนายจ้าง','personal cover':'ประกันส่วนตัว','own pay budget':'งบที่จ่ายเอง','custom':'กำหนดเอง','none':'ไม่มี','yes':'ใช่','no':'ไม่ใช่','deductible':'Deductible','copay':'Copay','both':'ทั้งสองแบบ','incomplete':'ข้อมูลไม่ครบ','review':'ตรวจทาน','room aligned':'ค่าห้องสอดคล้องกัน','health advice':'คำแนะนำสุขภาพ','ci advice':'คำแนะนำโรคร้ายแรง','health questions':'คำถามเรื่องสุขภาพ','life method':'วิธีคำนวณประกันชีวิต','ci method':'วิธีคำนวณโรคร้ายแรง','health method':'วิธีคำนวณสุขภาพ','privacy':'ความเป็นส่วนตัว','pending':'กำลังดำเนินการ','complete prompt':'คำแนะนำให้กรอกข้อมูลครบ','invalid':'ข้อมูลไม่ถูกต้อง','warning':'คำเตือน','reset':'ปุ่มเริ่มใหม่','attached':'ข้อความแนบผลแล้ว','calculator botanical background':'ภาพพื้นหลังเครื่องคำนวณ','calculator optional photo':'รูปเครื่องคำนวณ (ไม่บังคับ)',
  'error illustration (leave centre blank for status number)':'ภาพหน้า Error (เว้นกลางภาพสำหรับรหัส)','eyebrow':'ข้อความเหนือหัวข้อ','missing':'ไม่พบหน้า','missing body minimal':'คำอธิบายสั้นเมื่อไม่พบหน้า','denied':'ไม่มีสิทธิ์เข้าถึง','busy':'คำขอมากเกินไป','server':'ระบบขัดข้อง','timeout':'หมดเวลารอ','generic':'ข้อผิดพลาดทั่วไป','home':'หน้าแรก','back':'ปุ่มย้อนกลับ','retry pending':'ข้อความขณะลองใหม่','code label':'คำกำกับรหัส Error','popular':'เมนูยอดนิยม','motor':'ประกันรถยนต์','contact':'ช่องทางติดต่อ','help title':'หัวข้อความช่วยเหลือ','help body':'รายละเอียดความช่วยเหลือ','skip':'ข้ามไปเนื้อหา',
  'banner heading':'หัวข้อแบนเนอร์','banner explanation':'คำอธิบายแบนเนอร์','allow analytics':'ปุ่มอนุญาต Analytics','decline analytics':'ปุ่มไม่อนุญาต Analytics','footer settings button':'ปุ่มตั้งค่าใน Footer','details disclosure':'ปุ่มดูรายละเอียด','cookie details':'รายละเอียดคุกกี้','choice and withdrawal explanation':'คำอธิบายการเลือกและถอนความยินยอม','google privacy link':'ลิงก์ความเป็นส่วนตัวของ Google','allowed status':'สถานะอนุญาต','declined status':'สถานะไม่อนุญาต','close without changes':'ปุ่มปิดโดยไม่เปลี่ยนแปลง',
  'motor insurer logo note':'หมายเหตุโลโก้บริษัทประกันรถ','comparison: class heading':'ตารางเปรียบเทียบ: หัวข้อชั้นประกัน','comparison: suitability heading':'ตารางเปรียบเทียบ: หัวข้อความเหมาะสม','story: event heading':'เคสตัวอย่าง: หัวข้อเหตุการณ์','story: response heading':'เคสตัวอย่าง: หัวข้อการช่วยเหลือ','hero background artwork':'ภาพพื้นหลัง Hero','licence section: eyebrow':'ส่วนใบอนุญาต: ข้อความเหนือหัวข้อ','licence section: heading':'ส่วนใบอนุญาต: หัวข้อ','licence section: statement':'ส่วนใบอนุญาต: ข้อความสรุป','licence section: background artwork':'ส่วนใบอนุญาต: ภาพพื้นหลัง','optional hero statement':'ข้อความเสริม Hero (ไม่บังคับ)','optional about teaser':'ข้อความแนะนำเรา (ไม่บังคับ)','read more':'ปุ่มอ่านเพิ่มเติม','full comparison':'ปุ่มดูตารางเปรียบเทียบเต็ม','motor page link':'ลิงก์หน้าประกันรถ','navigation menu':'เมนูนำทาง','close menu':'ปุ่มปิดเมนู','optional form details':'รายละเอียดฟอร์ม (ไม่บังคับ)','contact channels heading':'หัวข้อช่องทางติดต่อ','form heading':'หัวข้อฟอร์ม','form introduction':'ข้อความนำฟอร์ม','line label':'ข้อความช่องทาง LINE','facebook helper':'คำอธิบาย Facebook','hours label':'หัวข้อเวลาทำการ','service area label':'หัวข้อพื้นที่บริการ','reassurance':'ข้อความสร้างความมั่นใจ','name placeholder':'ตัวอย่างในช่องชื่อ','contact placeholder':'ตัวอย่างในช่องติดต่อ','details placeholder':'ตัวอย่างในช่องรายละเอียด','background artwork':'ภาพพื้นหลัง','area':'พื้นที่บริการ','form':'ฟอร์ม','licence introduction':'ข้อความนำใบอนุญาต','navigation introduction':'ข้อความนำเมนู','contact introduction':'ข้อความนำช่องทางติดต่อ','closing statement':'ข้อความปิดท้าย','closing brand line':'ข้อความแบรนด์ปิดท้าย','licence':'ใบอนุญาต','nav':'เมนู','updated consent notice':'แจ้งข้อความยินยอมเปลี่ยนแปลง','form unavailable notice':'แจ้งฟอร์มไม่พร้อมใช้งาน','return to consultation':'ปุ่มกลับไปปรึกษา','fees':'ค่าตอบแทน','transparency note':'หมายเหตุความโปร่งใส','fees: heading statement':'ค่าตอบแทน: ข้อความหัวข้อ','privacy: heading statement':'ความเป็นส่วนตัว: ข้อความหัวข้อ','fees: note heading':'ค่าตอบแทน: หัวข้อหมายเหตุ','privacy: note heading':'ความเป็นส่วนตัว: หัวข้อหมายเหตุ','fees: closing statement':'ค่าตอบแทน: ข้อความปิดท้าย','privacy: closing statement':'ความเป็นส่วนตัว: ข้อความปิดท้าย','explicit calculator sharing':'ข้อความยินยอมแนบผลคำนวณ','insurer logo note':'หมายเหตุโลโก้บริษัทประกัน','matrix: covered':'ตาราง: คุ้มครอง','matrix: conditional':'ตาราง: มีเงื่อนไข','matrix: not covered':'ตาราง: ไม่คุ้มครอง','offline form message':'ข้อความฟอร์มเมื่อ Offline','unconfirmed submission':'ข้อความเมื่อยืนยันผลส่งไม่ได้','consultation summary':'สรุปคำขอปรึกษา','consultation summary without calculator':'สรุปคำขอโดยไม่มีผลคำนวณ','summary enquiry label':'คำกำกับหัวข้อในสรุป','summary coverage label':'คำกำกับความคุ้มครองในสรุป','renewal request summary':'สรุปคำขอเตือนต่ออายุ','renewal selection hint':'คำแนะนำเลือกข้อมูลต่ออายุ','renewal summary preview':'Preview สรุปต่ออายุ',
  'heading':'หัวข้อ','description':'คำอธิบาย','primary button':'ปุ่มหลัก','secondary button':'ปุ่มรอง','supporting note':'หมายเหตุเสริม','trust: unit-linked policy':'ข้อมูลสร้างความมั่นใจ: Unit-linked','trust: exclusions':'ข้อมูลสร้างความมั่นใจ: ข้อยกเว้น','trust: claims support':'ข้อมูลสร้างความมั่นใจ: ช่วยเหลือเคลม','topic prompt':'ข้อความให้เลือกหัวข้อ','coverage prompt':'ข้อความให้เลือกความคุ้มครอง','policy prompt':'ข้อความให้เลือกกรมธรรม์','month prompt':'ข้อความให้เลือกเดือน','query / quote':'หัวข้อ / ขอใบเสนอราคา','query / compare':'หัวข้อ / เปรียบเทียบ','query / general':'หัวข้อ / สอบถามทั่วไป','query / review':'หัวข้อ / ตรวจกรมธรรม์','query / claim':'หัวข้อ / เคลม','coverage / life':'ความคุ้มครอง / ชีวิต','coverage / health':'ความคุ้มครอง / สุขภาพ','coverage / motor':'ความคุ้มครอง / รถยนต์','coverage / accident':'ความคุ้มครอง / อุบัติเหตุ','coverage / savings':'ความคุ้มครอง / ออมทรัพย์','coverage / unsure':'ความคุ้มครอง / ยังไม่แน่ใจ','renewal / motor':'ต่ออายุ / รถยนต์','renewal / compulsory':'ต่ออายุ / พ.ร.บ.','renewal / health':'ต่ออายุ / สุขภาพ','renewal / life':'ต่ออายุ / ชีวิต','renewal / accident':'ต่ออายุ / อุบัติเหตุ',
  'service area':'พื้นที่ให้บริการ','expertise (one per line)':'ความเชี่ยวชาญ (บรรทัดละรายการ)','home service name':'ชื่อบริการหน้าแรก','motor service name':'ชื่อบริการหน้าประกันรถ','home service type':'ประเภทบริการหน้าแรก','motor service type':'ประเภทบริการหน้าประกันรถ','home audience':'กลุ่มเป้าหมายหน้าแรก','motor audience':'กลุ่มเป้าหมายหน้าประกันรถ','situation':'สถานการณ์','hint':'คำแนะนำ','estimate for':'คำกำกับผู้รับผลประเมิน','life need':'ทุนชีวิตที่ต้องการ','ci buffer':'เงินสำรองโรคร้ายแรง','send':'ปุ่มส่ง','policy':'ประเภทกรมธรรม์','month':'เดือน','consent':'ความยินยอม','submit':'ปุ่มส่งข้อมูล','scan':'ข้อความสแกน','name':'ชื่อ','topic':'หัวข้อที่สนใจ','coverage':'ความคุ้มครอง','header logo':'โลโก้ Header','footer logo':'โลโก้ Footer','brand icon':'ไอคอนแบรนด์','life focus: licence icon':'ประกันชีวิต: ไอคอนใบอนุญาต','life focus: unit-linked policy icon':'ประกันชีวิต: ไอคอน Unit-linked','life focus: exclusions icon':'ประกันชีวิต: ไอคอนข้อยกเว้น','life focus: claims icon':'ประกันชีวิต: ไอคอนเคลม','advisor photo':'รูปผู้ให้คำปรึกษา','advisor logo':'โลโก้ผู้ให้คำปรึกษา','line qr image':'รูป QR ของ LINE','favicon':'Favicon','social sharing image':'รูปแชร์บน Social media','social image description':'คำอธิบายรูปแชร์','life agent licence number':'เลขใบอนุญาตตัวแทนประกันชีวิต','life agent licence label':'คำกำกับใบอนุญาตตัวแทนประกันชีวิต','life provider logo':'โลโก้บริษัทประกันชีวิต','life provider logo description':'คำอธิบายโลโก้บริษัทประกันชีวิต','non-life broker licence number':'เลขใบอนุญาตนายหน้าประกันวินาศภัย','non-life broker licence label':'คำกำกับใบอนุญาตนายหน้าประกันวินาศภัย','non-life provider logo':'โลโก้บริษัทประกันวินาศภัย','non-life provider logo description':'คำอธิบายโลโก้บริษัทประกันวินาศภัย','placement broker licence number':'เลขใบอนุญาตบริษัทนายหน้าผู้จัดวางประกัน','licence verification link':'ลิงก์ตรวจสอบใบอนุญาต','licence verification label':'ข้อความลิงก์ตรวจสอบใบอนุญาต','licence heading':'หัวข้อใบอนุญาต','navigation heading':'หัวข้อเมนู','contact heading':'หัวข้อติดต่อ','advisor heading':'หัวข้อผู้ให้คำปรึกษา','coverage cards heading':'หัวข้อการ์ดความคุ้มครอง','call button description':'คำอธิบายปุ่มโทร','consultation consent':'ความยินยอมฟอร์มปรึกษา','submission failed':'ข้อความส่งไม่สำเร็จ','submission pending':'ข้อความกำลังส่ง','submission successful':'ข้อความส่งสำเร็จ'
};

function cmsAdminLabel(label) {
  const key = String(label).replace(/([a-z])([A-Z])/g, '$1 $2').toLowerCase().trim();
  if (CMS_ADMIN_LABELS[key]) return CMS_ADMIN_LABELS[key];
  // Repeated schema labels have predictable suffixes; saved content never enters here.
  for (const [suffix, prefix] of [[' input icon','ไอคอนช่อง '],[' tab icon','ไอคอนแท็บ '],[' icon override','ไอคอน '],[' subtitle','คำบรรยาย '],[' help','คำแนะนำ: '],[' title','หัวข้อ: '],[' body','คำอธิบาย: '],[' intro','ข้อความนำ: '],[' line','ปุ่ม LINE: '],[' optional','ข้อความเพิ่มเติม: ']]) {
    if (key.endsWith(suffix) && CMS_ADMIN_LABELS[key.slice(0, -suffix.length)]) return prefix + CMS_ADMIN_LABELS[key.slice(0, -suffix.length)];
  }
  return label;
}

function cmsAdminMediaLabel(slot) {
  const field = CMS_CONTENT_FIELDS.find(field => slot.path === field.path || slot.path === field.path + '.th' || slot.path === field.path + '.en');
  if (field) return cmsAdminLabel(field.label) + (field.localized ? ' (' + slot.path.split('.').at(-1).toUpperCase() + ')' : '');
  if (slot.path === 'brand.advisorLogo') return 'โลโก้ผู้ให้คำปรึกษา';
  // Dynamic item names are owner content; retain them and translate only the media kind.
  return slot.label.replace(/ \/ (logo|illustration|photo|icon)$/, (_, kind) => ' / ' + ({logo:'โลโก้',illustration:'ภาพประกอบ',photo:'รูปภาพ',icon:'ไอคอน'}[kind]));
}

function cmsAdminItemLabel(key) {
  return {chip:'ข้อความสั้น',card:'การ์ด',step:'ขั้นตอน',insurer:'บริษัทประกัน','insurer card':'การ์ดบริษัทประกัน',tier:'ชั้นประกัน',quote:'รีวิว',fact:'ข้อมูล',question:'คำถาม','contact tile':'ช่องทางติดต่อ',reason:'เหตุผล',check:'รายการตรวจสอบ',row:'แถว',story:'เคสตัวอย่าง','licence card':'การ์ดใบอนุญาต',item:'รายการ'}[key] || key;
}
